Repository Arriving-B/Front-End, pull requests merged in 2024-05, with the labels that each got.

#7 Design : Completed main page basic frame
  src/App.tsx
  src/assets/header/Gps_icon_off.png
  src/assets/header/Gps_icon_on.png
  src/assets/header/main_icon.png
  src/assets/header/reset_icon.png
  src/assets/header/search_icon.png
  src/assets/header/setting_icon.png
  src/components/header/header.tsx
  src/index.css
Labels: Design

#9 Design : Complete Infrom Component
  src/components/InfromBoard.tsx
Labels: Design

#13 [Design] 메인페이지 퍼블리싱 최종
  src/App.tsx
  src/assets/mainpage/bus.png
  src/components/mainPage/ArrivingBusList.tsx
  src/pages/MainPage.tsx
Labels: Design

#15 [Chore] 메인 브랜치 업데이트
  .eslintrc.cjs
  .prettierrc
  .vite/deps/_metadata.json
  .vite/deps/chunk-XFZ2DVVZ.js
  .vite/deps/react-dom_client.js
  .vite/deps/react.js
  README.md
  package.json
  src/App.css
  src/App.tsx
  src/assets/mainpage/bus.png
  src/components/header/Header.tsx
  src/components/header/header.tsx
  src/components/mainPage/ArrivingBusList.tsx
  src/index.css
  src/pages/BusInformPage.tsx
  src/pages/MainPage.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: Design, Chore

#16 Design : Publishing BusInfromPage
  .eslintrc.cjs
  src/components/BusInform/SmallInformBox.tsx
  src/components/InfromBoard.tsx
  src/components/header/Header.tsx
  src/pages/BusInformPage.tsx
  vite.config.ts
Labels: Design

#17 [Design] 헤더 디자인 고도화
  package-lock.json
  package.json
  src/App.tsx
  src/components/header/Header.tsx
  src/index.css
  yarn.lock
Labels: Feature, Design

#19 [Feature] 메인페이지 API 연동
  package.json
  src/components/mainPage/ArrivingBusList.tsx
  src/pages/MainPage.tsx
  src/store/busListStore.tsx
  src/store/stationStore.tsx
  yarn.lock
Labels: Feature

#21 [Feature] 페이지 라우터 구현
  package-lock.json
  src/App.tsx
  src/components/InfromBoard.tsx
  src/components/header/Header.tsx
  src/index.css
  src/pages/BusInformPage.tsx
  src/pages/MainPage.tsx
  yarn.lock
Labels: Refactor, Feature

#22 [design] busInfromPublishing 및 기초 기능 구현
  src/App.tsx
  src/components/BusInform/SmallInformBox.tsx
  src/components/InfromBoard.tsx
  src/index.css
  src/pages/BusInformPage.tsx
  src/store/busDetailStore.tsx
  src/store/busRouteListStore.tsx
Labels: Feature, Design

#26 refactor : 개선
  src/App.tsx
  src/components/InfromBoard.tsx
  src/pages/BusInformPage.tsx
  src/store/busDetailStore.tsx
  src/store/busRouteListStore.tsx
Labels: Fix, Refactor, Feature
